# Generated by Django 5.1.3 on 2025-01-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courses',
            new_name='faculty',
        ),
    ]
